spring.application.name=payment-service


server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=Kr02032003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

razorpay.key-id=rzp_test_SgcBNl06GmU4zh
razorpay.key-secret=2rcnttaMw4KWe9iTy0KnfVP0

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest